// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aupqouoacxvifsgizmhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1cHFvdW9hY3h2aWZzZ2l6bWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Nzk4MjUsImV4cCI6MjA1NTU1NTgyNX0.X4ISiKBl_gHZON-538BX7Z6AmWJ3Ql0plCwx_j31uHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);